org.gradle.jvmargs=-Xmx2G
net.minecraftforge.gradle.merge-source-sets=true
org.gradle.java.installations.paths=C\:\\Users\\2237n\\AppData\\Local\\Programs\\Eclipse Adoptium\\jdk-17.0.19+10,C\:\\Program Files\\Eclipse Adoptium\\jdk-21.0.9.10-hotspot
minecraft_version=1.21.7
forge_version=57.0.0
mod_id=adachirei_nui
mod_version=1.21.7-1.1.5
maven_group=dev._0yh
archives_base_name=AdachiRei-nui
