pluginManagement {
    repositories {
        gradlePluginPortal()
        maven {
            name = 'MinecraftForge'
            url = 'https://maven.minecraftforge.net/'
        }
        maven {
            name = 'SpongePowered'
            url = 'https://repo.spongepowered.org/repository/maven-public/'
        }
    }
    resolutionStrategy {
        eachPlugin {
            if (it.requested.id.namespace == 'org.spongepowered') {
                it.useModule('org.spongepowered:mixingradle:0.7.+')
            }
        }
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'AdachiRei-nui'
