modLoader="javafml"
loaderVersion="[1,)"
license="MIT"
issueTrackerURL="https://github.com/yh2237/AdachiRei-nui/issues"

[[mods]]
modId="adachirei_nui"
version="${mod_version}"
displayName="AdachiRei-nui"
logoFile="icon.png"
credits="yh"
authors="yh"
description='Adds Adachi Rei plushies to Minecraft'
displayURL="https://modrinth.com/mod/adachirei-nui"
updateJSONURL=""

[[mixins]]
config="adachirei_nui.mixins.json"

[[dependencies.adachirei_nui]]
    modId="neoforge"
    type="required"
    versionRange="[21.3,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.adachirei_nui]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.3]"
    ordering="NONE"
    side="BOTH"
